version: "3.8"

services:
  appredin:
    image: cristianimg:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.appredin.entrypoints: "http"
        traefik.http.routers.appredin.rule: "Host(`appredin.byronrm.com`)"
        traefik.http.middlewares.appredin-https-redirect.redirectscheme.scheme: "https"
        traefik.http.routers.appredin.middlewares: "appredin-https-redirect"
        traefik.http.routers.appredin-secure.entrypoints: "https"
        traefik.http.routers.appredin-secure.rule: "Host(`appredin.byronrm.com`)"
        traefik.http.routers.appredin-secure.tls: "true"
        traefik.http.routers.appredin-secure.tls.certresolver: "http"
        traefik.http.routers.appredin-secure.service: "appredin"
        traefik.http.services.appredin.loadbalancer.server.port: "80"  # Asegúrate de que tu app escucha en el puerto 80 dentro del contenedor
        traefik.docker.network: "traefik-public"
    networks:
      - traefik-public
    ports:
      - "80:80"  # Expón el puerto 80 para la comunicación externa

networks:
  traefik-public:
    external: true  # Asegúrate de que esta red externa esté creada en tu servidor
